[tool.pydocstyle]
convention = "google"
add-ignore = [
  "D100",  # Missing docstring in public module (будем добавлять постепенно)
  "D104",  # Missing docstring in public package
]
match = "(?!tests/).*\\.py"

[tool.mypy]
python_version = "3.9"
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
show_error_codes = true
exclude = [
  "tests/.*",
]
plugins = []

[tool.pytest.ini_options]
addopts = "-q --doctest-glob=*.py --doctest-modules"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]