   name: CI
   on:
     push:
       branches: [ "block-test" ]
     pull_request:
       branches: [ "block-test" ]
   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-python@v5
           with:
             python-version: "3.9"
         - name: Install deps
           run: |
             python -m pip install --upgrade pip
             pip install -r requirements.txt
         - name: Lint docstrings (pydocstyle)
           run: pydocstyle .
         - name: Type check (mypy)
           run: mypy .
         - name: Run tests (pytest)
           run: pytest
         - name: Build docs (MkDocs)